### ISSUE TITLE
Number of predictors in train method does not equal number of predictors in classify

### ISSUE THREAD

**Issue by evertrol** [GOTO-OBS/goto-vegas#3]
Testing this locally, it appears the number of columns/feature types given to the `train` method is 57 (that includes the "scores-" columns, see issue #2), while the number of features given to the `classify` method is only 41.
I do notice a number of columns showing up twice in the `predictors` argument of `train`.

It's not obvious how that happens. Am I missing something, or am I misinterpreting the arguments passed to the two methods?

**Comment by andycasey** [comment]
Currently `GOTO_01_*.csv.gz` and `GOTO_02_*.csv.gz` files are used for training, and `GOTO_03_*.csv.gz` and `GOTO_04_*.csv.gz` are used for testing.

Do those files all have the same columns? Otherwise, yes, there's no obvious way that this could happen.

**Comment by evertrol** [comment]
`GOTO_01_20170622_0001.csv` is borked: it has more columns than it should have.  
The other files are fine. I'll go and fix that file.

In the mean time, will anything fail if I remove that particular file for now? It looks like `download_data.py` will raise an exception, unless the relevant Travis environment variable is (temporarily) altered

**Comment by andycasey** [comment]
Nothing will fail, so that file can be fixed without worry.

**Comment by evertrol** [comment]
I'm not sure, but my first attempt failed on Travis, as follows:

```
$ python score.py
Traceback (most recent call last):
  File "score.py", line 52, in <module>
    classifier.train(training_set, training_set_classifications)
  File "/home/travis/build/GOTO-OBS/[secure]-vegas/classifier/classifier.py", line 33, in train
    self.clf.fit(df, classifications)
  File "/home/travis/miniconda/lib/python2.7/site-packages/sklearn/ensemble/forest.py", line 247, in fit
    X = check_array(X, accept_sparse="csc", dtype=DTYPE)
  File "/home/travis/miniconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 382, in check_array
    array = np.array(array, dtype=dtype, order=order, copy=copy)
ValueError: could not convert string to float: </html>

The command "python score.py" exited with 1.
```

This is *after* I removed the offending CSV file.
I'm guessing `download_data.py` attempts to download it, and gets a 404 error in HTML format. Since the requests response is not checked for being ok, it will happily save that error as a file, which is consequently read in by `score.py` (as a CSV file, nonetheless).

Perhaps I over-interpreted your statement that nothing will fail? I can probably create an empty CSV file with the correct header for now in its place instead.

**Comment by andycasey** [comment]
I've added a data-check in `.ci/download_data.py` -- you may need to rebase to master, then push a change to your branch on GitHub to get Travis to run properly.

(Or, upload the corrected CSV file)

**Comment by evertrol** [comment]
> (Or, upload the corrected CSV file)

Working on it!

**Comment by evertrol** [comment]
It looks like this one CSV file was ahead of its time: it included a few renamed features, and a few new ones. I probably used that file as a test case for extending the feature extraction step in the pipeline, and then accidentally included it with the other, not updated, CSV files.

I reverted the file to the stable type, and it should be equal (in columns) to all the other CSV files.
So all *.csv.gz files that are downloaded are now properly the same.
