### ISSUE TITLE
Feature/change request: use numpy arrays

### ISSUE THREAD

**Issue by evertrol** [GOTO-OBS/goto-vegas#5]
Astropy's `Table`, and especially it's `Row`, is messing around with me!

It's horrible to put it into some of `sklearn` classifiers prediction method, and I'm having trouble converting the `astropy.table.Row` (the `predictors` argument in `classify`) to something they will accept.

`sklearn` has no problem with Pandas DataFrames or Series, but those are not familiar to everyone. Perhaps the greatest common denominator is a numpy recarray?

I *will* manage to convert `Row` into something `sklearn.ensemble.RandomForestClassifier.predict()` accepts, but other people may run into similar issues, hence I'm putting this up as an issue/question.

**Comment by andycasey** [comment]
Is this still an issue with a vectorized `classify` function? Does something like:

````python
predictors_to_use = np.hstack([predictors[l] for l in ("nsig5", "nsig2")])
````

work and avoid the need for `pandas`?

**Comment by evertrol** [comment]
Seems to work now.

It's not the need to avoid Pandas, but the fact that an Astropy `Row` has no way to degrade nicely to a numpy array.  (A `Table` does reasonably well, so the vectorised classify version will be better.)
  
And also because more routines work on a numpy array than on an Astropy table or row (the aforementioned gcd).
