### ISSUE TITLE
Excellent idea

### ISSUE THREAD

**Issue by jrmullaney** [GOTO-OBS/goto-vegas#8]
This is a great idea guys!

Just to clarify. Is this to classify different types of transients (I guess transients vs. variables in the current sims), or is it to discriminate true and false positives? Or will it work for both?

**Comment by evertrol** [comment]
We don't have light curves (at the moment), so distinguishing between different types of transients will not be possible.
And, afaict, the scoring at this moment is a simple yes-or-no, hence it is to discriminate between transients and non-transients. For example, it can't yet distinguish between rubbish, transients and variables. This also makes it a bit easier to determine false positives.

But I could imagine this being extended in the future to multiple categories, as well as allowing for some level of probability assigned to each detection. It'll make the gamification of classification a bit harder (a classifier with 80% probability for each transient may outrank a classifier that ranks all its transients between 60% and 100% ; or not).

As for the transient type: we'll need light curves for that (with, perhaps, a few exceptions), and thus light curve database...

**Comment by andycasey** [comment]
Thanks @jrmullaney, but most of the credit probably should go to @outs1der and @evertrol 

@evertrol gave a good summary: for now it is just set up to classify transient candidates as true/false, but in future (given some data set) I could easily create another repository to test classifiers that will determine different kinds of transients (from junk).
